# Generated by Django 3.2.6 on 2021-08-06 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('passport', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cities', models.CharField(choices=[('Екатеринбург', 'Екатеринбург'), ('Елабуга', 'Елабуга'), ('Зеленодольск', 'Зеленодольск'), ('Иннополис', 'Иннополис'), ('Казань', 'Казань'), ('Краснодар', 'Краснодар'), ('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Сочи', 'Сочи')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)])),
                ('rate', models.CharField(choices=[('Ультра', 'Ультра'), ('Smart', 'Smart'), ('Безлимитище', 'Безлимитище'), ('Тарифище', 'Тарифище')], max_length=30)),
                ('balance', models.FloatField()),
                ('minutes', models.IntegerField()),
                ('internet', models.FloatField()),
                ('sms', models.IntegerField()),
                ('date_payment', models.DateField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telesystem.subscriber')),
            ],
        ),
    ]
